In [2]:
#Funtion to encrypt a data file
keyfile='Datafolder/key.txt'
def dictionaryKeyFile(keyfile):
    key={}
    with open(keyfile,'r') as f:
        for line in f:
            line=line.split()
            key[line[0]] =line[1]
    return key 
        
#def dataencription(datafile,keyfile):
    #Step 1: Construct a dictuonary for key data 
dictionaryKeyFile(keyfile)   
    
def encriptData(datafile,keyfile):
    key=dictionaryKeyFile(keyfile)
    with open(datafile,'r') as f:
        filedata=f.read().split('\n')
    with open('DataFolder/encryptedMarks.txt','w') as f:
        for mark in filedata:
            line=''
            for n in mark:
                line +=key[n]
            f.write(line+'\n')
    return
datafile='Datafolder/marks.txt'
encriptData(datafile,keyfile)

In [3]:
def dcriptData(encriptData,keyfile):
    key=dictionaryKeyFile(keyfile)
    newkey={}
    for key,value in key.items():
        newkey[value]=key
    with open(encriptData,'r') as f:
        encriptData=f.read().split('\n')
    with open('datafolder/decryptedMarks.txt','w') as f:
        
        for encriptedmark in encriptData:
            line=''
            for n in encriptedmark:
                line +=newkey[n]
            f.write(line+'\n')
    return

# encriptData='DataFloder/encryptedMarks.txt'
dcriptData('datafolder/encryptedMarks.txt','datafolder/key.txt')


In [4]:
# Comprehensions
keyfile='datafolder/key.txt'
key =dictionaryKeyFile(keyfile)
evenkeys={item for item in key}
evenkeys

{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}

In [2]:
n=int(input())
for i in range(n):
    s=int(input())
    print(s)

1
1
1


### Numpy Library
- Processing N-Dimentional Arrays 

In [3]:
import numpy as np

li = [1,2,3,'z']
a=np.array(li)
b=np.arange(15)
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
# Generating of random numbers 
rn=np.random.randint(0,100,size=10)
rn

array([24, 47, 75, 10, 94, 44, 14, 51, 50,  3])

In [5]:
#Three Dimentional Matrix
m3=np.random.randint(0,2,size=(3,3))
m3
#m3[0][1]

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [6]:
#Three Dimentional Matrix
m3=np.random.randint(0,2,size=(3,3,3,3))

m3[2][2][2][1]
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes


324

In [7]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [9]:
import numpy as np

#m3=np.random.randint(0,2,size=(3,3))
m=np.once((3,3))
print("Print matrix",m)


AttributeError: module 'numpy' has no attribute 'once'

In [ ]:
import timeit as t
st=t.default_timer()
print(t.default_timer()-st)

# Pandas
** Use Cases **
 - Data Cleaning 
 - Data Transformation
 - Data Analysis
* Notations 
    - Series 
    - DataFrames


In [ ]:
import pandas as pd

internal1={'s1':21,'s2':18,'s3':24,'s4':23}
internal1=pd.Series(internal1)
internal1
internal2={'s1':24,'s2':12,'s3':64,'s4':73}
internal2=pd.Series(internal2)
internal2

In [ ]:
final={'Internal1':internal1,'Internal2':internal2}
final=pd.DataFrame(final)
final

In [ ]:
final={'Internal1':internal1,'Internal2':internal2}
final=pd.DataFrame(final)
final['Internal1']

In [ ]:
final.columns#Names of all Columns

In [ ]:
final.values#Rows of the all data (list of all rows)

In [ ]:
final.values[2]#indexing of arrays

In [ ]:
final.values[2,0]#Accesing second coloum first row
final.values[2][0]

In [ ]:
for row in final.values:
    print('Internal1-', row[0],'Internal2-',row[1])

In [ ]:
final.loc[5]=[15,8]
final

In [ ]:
final.values[2]=[12,25]
final



In [1]:
final=final.drop('s1')
final

NameError: name 'final' is not defined

In [ ]:
#Reading CSV File Data at Pandas
import pandas as pd

filepath='datafolder/income.csv'
incomeDataFrame =pd.read_csv(filepath)
incomeDataFrame


In [ ]:
# Exacting Income of all states in 2013
#California:57525
incomeDataFrame.values

In [ ]:
# Exacting Income of all states in 2013
#California:57525
for row in incomeDataFrame.values:
    print(row[1],':',row[-1])
    

In [ ]:
#avg of a paticular state
sum=0
for i in range(2,11):
    sum+=incomeDataFrame.values[2][i]
#sum/len(incomeDataFrame.values[2][2:])
sum/9


In [ ]:
#Avg range of all states in year 2012
sum=0
for row in incomeDataFrame.values:
    sum+=row[-2]
sum/len(incomeDataFrame.values)

In [6]:
#Avg range of all states in year 2012
sum=0
for row in incomeDataFrame.values:
    sum+=row[0,10+1]
sum/len(incomeDataFrame.values)

NameError: name 'incomeDataFrame' is not defined