In [3]:
#Funtion to encrypt a data file
keyfile='Datafolder/key.txt'
def dictionaryKeyFile(keyfile):
    key={}
    with open(keyfile,'r') as f:
        for line in f:
            line=line.split()
            key[line[0]] =line[1]
    return key 
        
#def dataencription(datafile,keyfile):
    #Step 1: Construct a dictuonary for key data 
dictionaryKeyFile(keyfile)   
    
def encriptData(datafile,keyfile):
    key=dictionaryKeyFile(keyfile)
    with open(datafile,'r') as f:
        filedata=f.read().split('\n')
    with open('DataFolder/encryptedMarks.txt','w') as f:
        for mark in filedata:
            line=''
            for n in mark:
                line +=key[n]
            f.write(line+'\n')
    return
datafile='Datafolder/marks.txt'
encriptData(datafile,keyfile)

In [36]:
def dcriptData(encriptData,keyfile):
    key=dictionaryKeyFile(keyfile)
    newkey={}
    for key,value in key.items():
        newkey[value]=key
    with open(encriptData,'r') as f:
        encriptData=f.read().split('\n')
    with open('datafolder/decryptedMarks.txt','w') as f:
        
        for encriptedmark in encriptData:
            line=''
            for n in encriptedmark:
                line +=newkey[n]
            f.write(line+'\n')
    return

# encriptData='DataFloder/encryptedMarks.txt'
dcriptData('datafolder/encryptedMarks.txt','datafolder/key.txt')


NameError: name 'dictionaryKeyFile' is not defined

In [18]:
# Comprehensions
keyfile='datafolder/key.txt'
key =dictionaryKeyFile(keyfile)
evenkeys={item for item in key}
evenkeys

{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}

In [20]:
n=int(input())
for i in range(n):
    s=int(input())
    print(s)

2
5
5
7
7


### Numpy Library
- Processing N-Dimentional Arrays 

In [4]:
import numpy as np

li = [1,2,3,'z']
a=np.array(li)
b=np.arange(15)
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
# Generating of random numbers 
rn=np.random.randint(0,100,size=10)
rn

array([26, 15, 12, 67, 51, 93, 35, 74, 22, 11])

In [10]:
#Three Dimentional Matrix
m3=np.random.randint(0,2,size=(3,3))
m3
#m3[0][1]

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 1]])

In [24]:
#Three Dimentional Matrix
m3=np.random.randint(0,2,size=(3,3,3,3))

m3[2][2][2][1]
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes


324

In [25]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [29]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [31]:
import numpy as np

#m3=np.random.randint(0,2,size=(3,3))
m=np.once((3,3))
print("Print matrix",m)


AttributeError: module 'numpy' has no attribute 'once'

In [35]:
import timeit as t
st=t.default_timer()
print(t.default_timer()-st)

4.548300012174877e-05


# Pandas
** Use Cases **
 - Data Cleaning 
 - Data Transformation
 - Data Analysis
* Notations 
    - Series 
    - DataFrames


In [6]:
import pandas as pd

internal1={'s1':21,'s2':18,'s3':24,'s4':23}
internal1=pd.Series(internal1)
internal1
internal2={'s1':24,'s2':12,'s3':64,'s4':73}
internal2=pd.Series(internal2)
internal2

s1    24
s2    12
s3    64
s4    73
dtype: int64

In [7]:
final={'Internal1':internal1,'Internal2':internal2}
final=pd.DataFrame(final)
final

Internal1  Internal2
s1         21         24
s2         18         12
s3         24         64
s4         23         73

In [8]:
final={'Internal1':internal1,'Internal2':internal2}
final=pd.DataFrame(final)
final['Internal1']

s1    21
s2    18
s3    24
s4    23
Name: Internal1, dtype: int64

In [9]:
final.columns#Names of all Columns

Index(['Internal1', 'Internal2'], dtype='object')

In [11]:
final.values#Rows of the all data (list of all rows)

array([[21, 24],
       [18, 12],
       [24, 64],
       [23, 73]], dtype=int64)

In [12]:
final.values[2]#indexing of arrays

array([24, 64], dtype=int64)

In [14]:
final.values[2,0]#Accesing second coloum first row
final.values[2][0]

24

In [19]:
for row in final.values:
    print('Internal1-', row[0],'Internal2-',row[1])

Internal1- 21 Internal2- 24
Internal1- 18 Internal2- 12
Internal1- 24 Internal2- 64
Internal1- 23 Internal2- 73


In [22]:
final.loc[5]=[15,8]
final

Internal1  Internal2
s1         21         24
s2         18         12
s3         24         64
s4         23         73
3          15          8
5          15          8

In [33]:
final.values[2]=[12,25]
final



Internal1  Internal2
s1         21         24
s2         18         12
s3         12         25
s4         23         73
3          15          8
5          15          8

In [39]:
final=final.drop('s1')
final

Internal1  Internal2
s2         18         12
s3         12         25
5          15          8

In [42]:
#Reading CSV File Data at Pandas
import pandas as pd

filepath='datafolder/income.csv'
incomeDataFrame =pd.read_csv(filepath)
incomeDataFrame


GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [43]:
# Exacting Income of all states in 2013
#California:57525
incomeDataFrame.values

array([['04000US01', 'Alabama', 37150, 37952, 42212, 44476, 39980, 40933,
        42590, 43464, 41381],
       ['04000US02', 'Alaska', 55891, 56418, 62993, 63989, 61604, 57848,
        57431, 63648, 61137],
       ['04000US04', 'Arizona', 45245, 46657, 47215, 46914, 45739, 46896,
        48621, 47044, 50602],
       ['04000US05', 'Arkansas', 36658, 37057, 40795, 39586, 36538,
        38587, 41302, 39018, 39919],
       ['04000US06', 'California', 51755, 55319, 55734, 57014, 56134,
        54283, 53367, 57020, 57528]], dtype=object)

In [44]:
# Exacting Income of all states in 2013
#California:57525
for row in incomeDataFrame.values:
    print(row[1],':',row[-1])
    

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [46]:
#avg of a paticular state
sum=0
for i in range(2,11):
    sum+=incomeDataFrame.values[2][i]
#sum/len(incomeDataFrame.values[2][2:])
sum/9


47214.77777777778

In [48]:
#Avg range of all states in year 2012
sum=0
for row in incomeDataFrame.values:
    sum+=row[-2]
sum/len(incomeDataFrame.values)

50038.8